---
include:
  - board: nice_nano_v2 
    shield: temper_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: temper_right nice_view_adapter nice_view
  - board: nice_nano_v2 
    shield: settings_reset
